# This example provisioner limits the amount of compute
# provisioned by Karpenter to 100 CPU cores

apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  limits:
    resources:
      cpu: 200
  consolidation:
    enabled: true
  providerRef:
    name: my-provider
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: my-provider
spec:
  subnetSelector:
    karpenter.sh/discovery: "eks-workshop" # replace with your cluster name
  securityGroupSelector:
    karpenter.sh/discovery: "eks-workshop" # replace with your cluster name

